## ------------------------------------------------------- 
## docker-compose.yml for  basicrobot with front-end 
## -------------------------------------------------------
version: "3.8"
services:
  frontend:
    build: C:/Progetti/Evolution/it.unibo.springboot.qak    
    #image:  frontendqak20basicrobot
    #image:   springbootqak
    depends_on:
     - basicrobot
    ports:             #HOST:CONTAINER
     - "8080:8080"
    environment:
       - "SPRING_PROFILES_ACTIVE=docker"    
  basicrobot:
    build: ../it.unibo.qak20.basicrobot
    #image:  basicrobotqak20
    ports:             #HOST:CONTAINER
     - "8020:8020/udp"
     - "8020:8020/tcp"


#docker-compose up --build -d 
#docker-compose logs